### ISSUE TITLE
NetBash tries to make ajax call to the root

### ISSUE THREAD

**Issue by mivano** [lukencode/NetBash#6]
I placed NetBash inside a webapplication hosted in a virtual directory. Whenever I type a command, the request is sent to http://localhost/netbash?Command=help and not to the virtual directory. This means that none of the commands work.

Anything to change in config maybe or is this a bug?

**Comment by lukencode** [comment]
This is most likely a bug there is a property for RouteBasePath in the settings class but I haven't tried it yet (code borrowed from mvcminiprofiler which does something similar)

The idea is you do something like this on application start:
    NetBash.Settings.RouteBasePath = "~/virtualfoldername"

Give it a go and see if you get lucky, otherwise its something that needs to be fixed.

**Comment by mivano** [comment]
Nope, that generates a 404 loading the netbash-script-js because it appends the virtual folder name twice.

**Comment by lukencode** [comment]
Ok, that shouldnt be too hard to fix. Will leave this open as a bug and try get to it. If you want to try fix it yourself the code that generates the paths is in UI/NetBashHandler.cs
